In [1]:
# Dependencies
import pandas as pd
import requests

# Hide warning messages in notebook
import warnings
warnings.filterwarnings('ignore')

In [2]:
# Data to store from the json
conflict_id=[]
year=[]
latitude=[]
longitude=[]
country=[]
country_id=[]
best=[]

# Loop through each page
for page in range(99):

    # Build query URL for each page
    query_url = "http://ucdpapi.pcr.uu.se/api/gedevents/18.1?pagesize=1000&page=" + str(page) + "&StartDate=2000-01-01"

    # get page data from API
    conflict_response = requests.get(query_url)
    conflict_json = conflict_response.json()
 
    if page == 99:
        recAmt = 173
    else:
        recAmt = 1000

    # Loop through each conflict item on the page
    for conflict in range(recAmt):
        conflict_id.append(conflict_json["Result"][conflict]["id"])
        year.append(conflict_json["Result"][conflict]["year"])
        latitude.append(conflict_json["Result"][conflict]["latitude"])
        longitude.append(conflict_json["Result"][conflict]["longitude"])
        country.append(conflict_json["Result"][conflict]["country"])
        country_id.append(conflict_json["Result"][conflict]["country_id"])
        best.append(conflict_json["Result"][conflict]["best"])

In [3]:
# Create dataframe to hold conflict data
conflict_data = {"Conflict Id": conflict_id,
                 "Year": year,
                 "Latitude": latitude,
                 "Longitude": longitude,
                 "Country": country,
                 "Country Id": country_id,
                 "Best Death Estimate": best
                }
conflict_df = pd.DataFrame(conflict_data)

# Clean up country names to match other dataframes
conflict_df.loc[conflict_df["Country"] == "Russia (Soviet Union)", "Country"] = "Russian Federation"
conflict_df.loc[conflict_df["Country"] == "DR Congo (Zaire)", "Country"] = "Congo"
conflict_df.loc[conflict_df["Country"] == "Macedonia, FYR", "Country"] = "FYR Macedonia"
conflict_df.loc[conflict_df["Country"] == "Cambodia (Kampuchea)", "Country"] = "Cambodia"
conflict_df.loc[conflict_df["Country"] == "Zimbabwe (Rhodesia)", "Country"] = "Zimbabwe"
conflict_df.loc[conflict_df["Country"] == "Serbia (Yugoslavia)", "Country"] = "Serbia"
conflict_df.loc[conflict_df["Country"] == "Madagascar (Malagasy)", "Country"] = "Madagascar"
conflict_df.loc[conflict_df["Country"] == "Yemen (North Yemen)", "Country"] = "Rep of Yemen"
conflict_df.loc[conflict_df["Country"] == "Myanmar (Burma)", "Country"] = "Myanmar"
conflict_df.loc[conflict_df["Country"] == "Ivory Coast", "Country"] = "Cote-d-Ivoire"
conflict_df.loc[conflict_df["Country"] == "Iran", "Country"] = "Islamic Republic of Iran"
conflict_df.loc[conflict_df["Country"] == "Laos", "Country"] = "Lao PDR"
conflict_df.loc[conflict_df["Country"] == "Venezuela", "Country"] = "RB-de-Venezuela"
conflict_df.loc[conflict_df["Country"] == "United States of America", "Country"] = "United States"

conflict_df.head()

,Conflict Id,Year,Latitude,Longitude,Country,Country Id,Best Death Estimate
0,217843,2002,43.507200,46.334000,Russian Federation,365,14
1,175934,2002,32.206406,35.286583,Israel,666,7
2,175981,2002,31.506792,35.027717,Israel,666,3
3,175983,2002,32.609067,35.289202,Israel,666,1
4,175984,2002,31.902561,35.195547,Israel,666,3

In [4]:
# Save the data:
conflict_df.to_csv('../1_Input/DF_Interim/worldconflict_data.csv', index=False, encoding='utf-8')